dns_name = "drivesmartcbus.com"
password = "***REMOVED***"
vpc_id = "***REMOVED***"
region = "us-east-1"
subnet_1 = "***REMOVED***"
send_to_email = "***REMOVED***"
environment = ""
ami_id = "***REMOVED***"